<?php

/**
 * @file
 * Contains benzinarie.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function benzinarie_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the benzinarie module.
    case 'help.page.benzinarie':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Se ocupa cu editarea si afisarea benzinariilor') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function benzinarie_theme() {
  $theme = [];

  return $theme;
}
