<?php

/**
 * @file
 * Contains user_blocks.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_blocks module.
    case 'help.page.user_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Displays user register and password forgotted blocks.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_blocks_theme() {
  $theme = [];

  return $theme;
}
