<?php

/**
 * @file
 * Contains harta.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function harta_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the harta module.
    case 'help.page.harta':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Afiseaza benzinariile pe harta si intr-un listing.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function harta_theme() {
  $theme = [];

  return $theme;
}
